name:                FizzBuzz1
version:             0.1.0.0
github:              kubek2k/FizzBuzz1
license:             BSD3
author:              Jakub Janczak
maintainer:          kubek2k@gmail.com
copyright:           2017 Jakub Janczak

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kubek2k/FizzBuzz1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  FizzBuzz1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FizzBuzz1

tests:
  FizzBuzz1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FizzBuzz1
    - QuickCheck
